title: Jonathan Berkheim
logo: "/images/logo.png?raw=true"
description: >
  PhD candidate at Weizmann Institute of Science
  <br><br>
  Sciencific communicator // Wikipedian // Public speaker
  <br><br>
  <a href="https://www.linkedin.com/in/jonathan-berkheim/">ğŸ” LinkedIn</a>
  <br><br>
  <a href="https://davidson.weizmann.ac.il/authors/×™×”×•× ×ª×Ÿ-×‘×¨×§×”×™×™×">âš›ï¸ Davidson Online</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
